### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by simlegate** [mulesoft/osprey#101]
I have added `"osprey": "^0.3.1"` to my package.json and exec `npm install`, but some errors appears on `Ubuntu 14.04.3 LTS` ( It's OK on OSX 10.9 ):

```shell
fatal: Not a git repository (or any of the parent directories): .git
[osprey-router@0.4.0] install error: Error: [router@git+https://github.com/blakeembrey/router#router-engine]: Run "sh -c git log -1 --format="%H"" error, exit code 128, parentDir: /home/vagrant/work/yamkit-estimate/node_modules/.npminstall/osprey/0.3.1/osprey, remove /home/vagrant/work/yamkit-estimate/node_modules/.npminstall/osprey-router/0.4.0/osprey-router
error stack: Error: [router@git+https://github.com/blakeembrey/router#router-engine]: Run "sh -c git log -1 --format="%H"" error, exit code 128
    at module.exports (/home/vagrant/.nvm/versions/node/v5.9.1/lib/node_modules/cnpm/node_modules/npminstall/lib/download/git.js:51:11)
    at throw (native)
    at onRejected (/home/vagrant/.nvm/versions/node/v5.9.1/lib/node_modules/cnpm/node_modules/co/index.js:81:24)
    at process._tickCallback (node.js:412:9)
[osprey@0.3.1] install error: Error: [router@git+https://github.com/blakeembrey/router#router-engine]: Run "sh -c git log -1 --format="%H"" error, exit code 128, parentDir: /home/vagrant/work/yamkit-estimate, remove /home/vagrant/work/yamkit-estimate/node_modules/.npminstall/osprey/0.3.1/osprey
error stack: Error: [router@git+https://github.com/blakeembrey/router#router-engine]: Run "sh -c git log -1 --format="%H"" error, exit code 128
    at module.exports (/home/vagrant/.nvm/versions/node/v5.9.1/lib/node_modules/cnpm/node_modules/npminstall/lib/download/git.js:51:11)
    at throw (native)
    at onRejected (/home/vagrant/.nvm/versions/node/v5.9.1/lib/node_modules/cnpm/node_modules/co/index.js:81:24)
    at process._tickCallback (node.js:412:9)
Error: [router@git+https://github.com/blakeembrey/router#router-engine]: Run "sh -c git log -1 --format="%H"" error, exit code 128
Error: [router@git+https://github.com/blakeembrey/router#router-engine]: Run "sh -c git log -1 --format="%H"" error, exit code 128
    at module.exports (/home/vagrant/.nvm/versions/node/v5.9.1/lib/node_modules/cnpm/node_modules/npminstall/lib/download/git.js:51:11)
    at throw (native)
    at onRejected (/home/vagrant/.nvm/versions/node/v5.9.1/lib/node_modules/cnpm/node_modules/co/index.js:81:24)
    at process._tickCallback (node.js:412:9)
```
@blakeembrey Could you help me check it ?

**Comment by blakeembrey** [comment]
@simlegate Seems like an issue with cloning a GitHub dependency. Is there any network issues affecting GitHub access when you do an `npm install`? I'll aim for a more long-term solution ASAP, by publishing the dependency onto NPM.

**Comment by simlegate** [comment]
@blakeembrey the Ubuntu system is a virtual machine on my macbook that the installation is OK, so I don't think it's a network issues

**Comment by sundar-nsm** [comment]
@blakeembrey i am facing same issue. 

`npm ERR! git clone --template=C:\Users\sslap\AppData\Roaming\npm-cache\_git-remo
tes\_templates --mirror https://github.com/blakeembrey/router.git C:\Users\sslap
\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-blakeembrey-router-
git-router-engine-0075f85f: undefined
npm ERR! git clone --template=C:\Users\sslap\AppData\Roaming\npm-cache\_git-remo
tes\_templates --mirror https://github.com/blakeembrey/router.git C:\Users\sslap
\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-blakeembrey-router-
git-router-engine-0075f85f: undefined`

**Comment by blakeembrey** [comment]
@sundar-nsm Are you also using `cnpm`?

**Comment by simlegate** [comment]
@blakeembrey 
 Maybe it was caused by `cnpm`, because the package is installed with `npm` successfully .
but I don't know what happen.

**Comment by simlegate** [comment]
@blakeembrey Could you give me some examples using the package with `koa` ?

**Comment by blakeembrey** [comment]
@simlegate It accepts `request` and `response`, so theoretically you can use it with something like https://github.com/vkurchatkin/koa-connect.

**Comment by simlegate** [comment]
@blakeembrey  Thank you very much and I will close the issue.
