### ISSUE TITLE
Question: Is this project still active?

### ISSUE THREAD

**Issue by jcheroske** [mulesoft/osprey#110]
I'm beginning a new REST api project and just discovered this repo. Are there plans to ramp up development here again? If not, is there another repo that has replaced this one? Thanks.

**Comment by jstoiko** [comment]
@jcheroske: yes, it is and we're currently working on adding [support for RAML 1.0](https://github.com/mulesoft/osprey/milestone/1).

**Comment by jcheroske** [comment]
Have you seen the express-openapi module? I'm curious about the future
viability of RAML given what's happening in that space.

Thank you for the reply.

**Comment by sichvoge** [comment]
That's more than a tough question and obviously not easy to answer in here. OpenAPI (aka Swagger) is a very good step forward, no doubt. Still, people prefer RAML for their specific use cases where Swagger is limited. It really depends on your specific scenarios and what helps you most. RAML does a very good job being very dry in its approach and people love that. Thats why it also gains a bit more popularity at the moment.

In the end its fully up to you what fits best tho ;)

**Comment by Gpx** [comment]
I'm also about to start document my API and I saw this repo didn't get updated in a month or so. Do you have an ETA for 1.0 support? Thanks

**Comment by jstoiko** [comment]
v0.4.0 with RAML 1.0 support has been [released](https://github.com/mulesoft/osprey/releases/tag/v0.4.0)
