### ISSUE TITLE
`Unable to compile JSON schema` error when POST refers to schemas in `schemas`

### ISSUE THREAD

**Issue by jstoiko** [mulesoft/osprey#115]
When loading the following example in Osprey: https://github.com/raml-org/raml-examples/blob/master/schemas/api.raml, error is:

```
SyntaxError: Unable to compile JSON schema for post /person: Unexpected token P in JSON at position 0
```

**Comment by jardilio** [comment]
I had the same issue with 2 other projects I'm using this with. To work around it, I had to load the raml via raml-parser, then manually cycle thru my schemas and add them to osprey which delegates all the way down to ajv for validation.

(raml.schemas || []).forEach(schemas => Object.keys(schemas).forEach(key => osprey.addJsonSchema(JSON.parse(schemas[key]), key)));

**Comment by andrew-kratik** [comment]
Hi team
Tried the same example as @jstoiko and got error
```
#%RAML 1.0
title: Using XML and JSON Schema

schemas: # can also be used with 'types'
  PersonInline: |
    {
      "title": "Person Schema",
      "type": "object",
      "properties": {
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "age": {
          "description": "Age in years",
          "type": "integer",
          "minimum": 0
        }
      },
      "required": ["firstName", "lastName"]
    }
  PersonInclude: !include person.json

/person:
  get:
    responses:
      200:
        body:
          application/json:
            schema: PersonInline # can also be used with 'type'
  post:
    body:
      application/json:
        schema: PersonInclude
```
person.json
```
{
  "title": "Person Schema",
  "type": "object",
  "properties": {
    "firstName": {
      "type": "string"
    },
    "lastName": {
      "type": "string"
    },
    "age": {
      "description": "Age in years",
      "type": "integer",
      "minimum": 0
    }
  },
  "required": ["firstName", "lastName"]
}
```
running `osprey-mock-service -f api.raml -p3000`
result:
```
SyntaxError: Unable to compile JSON schema for post /person: Unexpected token P in JSON at position 0
    at JSON.parse (<anonymous>)
    at jsonBodyValidationHandler (C:\java\nvm\v7.8.0\node_modules\osprey-mock-service\node_modules\osprey-method-handler\osprey-method-handler.js:438:21)
    at jsonBodyHandler (C:\java\nvm\v7.8.0\node_modules\osprey-mock-service\node_modules\osprey-method-handler\osprey-method-handler.js:361:21)
    at C:\java\nvm\v7.8.0\node_modules\osprey-mock-service\node_modules\osprey-method-handler\osprey-method-handler.js:295:29
    at Array.forEach (native)
    at C:\java\nvm\v7.8.0\node_modules\osprey-mock-service\node_modules\osprey-method-handler\osprey-method-handler.js:291:14
    at Array.forEach (native)
    at bodyHandler (C:\java\nvm\v7.8.0\node_modules\osprey-mock-service\node_modules\osprey-method-handler\osprey-method-handler.js:279:9)
    at ospreyMethodHandler (C:\java\nvm\v7.8.0\node_modules\osprey-mock-service\node_modules\osprey-method-handler\osprey-method-handler.js:105:21)
    at C:\java\nvm\v7.8.0\node_modules\osprey-mock-service\node_modules\osprey\lib\server.js:39:12
```

using osprey-mock-service@0.2.1

**Comment by jstoiko** [comment]
@andrew-kratik: it works for me using the latest version of Osprey and osprey-mock-service.

```
$ npm install -g osprey-mock-service
...
$ git clone git@github.com:raml-org/raml-examples.git
...
$ cd raml-examples/schemas/
$ osprey-mock-service -f api.raml -p3000
Mock service running at http://localhost:3000
```

I also tried using the same version of node as in your snippet (v7.8.0) and it worked fine. I suspect an issue with your global dependencies. Maybe try `npm uninstall -g osprey-mock-service` and then `npm install -g osprey-mock-service` again?

**Comment by andrew-kratik** [comment]
hi @jstoiko, yes it worked for me as well, but when I change line 32 from ``schema: PersonInline`` to ``schema: PersonInclude`` so it uses **included** schema but not **Inlined** as in original example - get error ``Unable to compile JSON schema for post /person: Unexpected token P in JSON...`` (that's why I pasted listing to previous comment)

**Comment by andrew-kratik** [comment]
Tried to reinstall, but the new version of ``osprey-mock-service`` has the same version as old. And issue the same when starting
+-- osprey-mock-service@0.2.1

the list of all global packages:
+-- abao@0.5.0
+-- api-designer@0.4.1
+-- localapi@1.6.0
+-- npm@4.2.0
+-- osprey-mock-service@0.2.1
+-- raml-mockup@0.2.1
+-- raml-server@0.1.6
+-- raml2boot@0.1.8
+-- raml2html@3.0.1
+-- raml2html-markdown-theme@1.0.1
+-- raml2html-slate-theme@1.0.0
`-- request@2.81.0

**Comment by jstoiko** [comment]
> when I change line 32 from schema: PersonInline to schema: PersonInclude

I tried that but it still works (no errors).

Can you share the output of `npm ls -g | grep osprey`?

**Comment by jstoiko** [comment]
Closing this old issue since it cannot be reproduced. Please re-open a new issue if it can be reproduced with the latest version of Osprey.
