### ISSUE TITLE
Accessing done() data, or URI data from basic_auth

### ISSUE THREAD

**Issue by hassanshaikley** [mulesoft/osprey#120]
How to access the route data from within basic_auth?

I want to authenticate the user and make sure that they have access to that resource. In order to do that I need to see which resource they are trying to reach and if they are the creator. 

If within this function I had access to the route they tried to access, to make sure you're authorized to view a file given your username and apiKey that would be great.

```
osprey.loadFile(path, {
	security: {
		basic_auth: {
			validateUser: function (username, apiKey, done) {

				const query = { $or: [{ accessToken: apiKey }] };
				User.findOne(query).lean().exec()
				.then((user) => {
					if (!user || user.username !== username) return done(null, false);
					return done(null, user);
				})
				.catch(error => done(error));
			}
		}
	}
})
```

**Comment by jstoiko** [comment]
It seems to me that you are trying to implement [`custom_auth`](https://github.com/mulesoft/osprey/blob/master/README.md#custom-security-schemes). You might want to use that instead, then you'll be able to access the [request data from within the handler](https://github.com/mulesoft/osprey/blob/master/examples/custom-auth/index.js#L11). Hope that helps.

**Comment by hassanshaikley** [comment]
Well, what I want is permissions with basic auth. I want to be able to check that a user has access to a resource, not only that a user is authenticated. I feel like that should be supported.
