### ISSUE TITLE
RAML 1.0 feedback please - anyone?

### ISSUE THREAD

**Issue by mbonaci** [mulesoft/osprey#122]
Hi,
although there are 2 existing issues around 1.0 support, I'm opening a new one since we can't seem to get anyone to respond to requests for timeline in neither of those.
Thanks

**Comment by jstoiko** [comment]
H @mbonaci, I'm sorry that you're not getting any update. [The work that brings RAML 1.0 support](https://github.com/mulesoft/osprey/pull/116) is currently being reviewed. We've had a few exchanges with the team in the past few days and a new version of Osprey should be released in the next week or so. In the meantime, feel free to give that `raml1.0` branch a try :-)
