### ISSUE TITLE
Support `$ref` for local paths

### ISSUE THREAD

**Issue by alexec** [mulesoft/osprey#123]
Osprey doesn't support `$ref` for local paths. Please support it.

**Comment by jstoiko** [comment]
@alexec: are you referring to the JSON schema `$ref` property? 

If so, JSON pointers referring to the same document, e.g. `{ "$ref": "#/definitions/reference" }`, should work out of the box. However, pointers to external files, e.g. `{ "$ref": "definitions.json#/reference" }` require [this extra step](https://github.com/mulesoft/osprey#add-json-schemas) (Osprey relies on [AJV](https://github.com/epoberezkin/ajv) to handle JSON schemas).

Feel from to copy/paste your RAML and JSON schema files here.
