### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by jy95** [mulesoft/osprey#130]
Hello,

I got this when I use the raml 1.0 branch with my file

[SCREEN](http://www.zupimages.net/up/17/08/ep64.png)

Just why ?

I use a raml file that includes a library raml file (for types)

PS: I will include an example soon.

**Comment by jstoiko** [comment]
I came across this [issue](https://github.com/raml-org/raml-js-parser-2/issues/628) on the JS parser that Osprey relies on. This seems related. Maybe you can test your RAML with the latest version of the parser and tell me if it fixes your issue. If it does, we can bump the version before releasing the new version of Osprey.

**Comment by jy95** [comment]
Alright. Just only need local command for osprey (in global installation, I cannot change the version)

**Comment by jstoiko** [comment]
if you use load your file with the parser directly like in the example of [this description](https://github.com/raml-org/raml-js-parser-2/issues/628), you should be able to reproduce the error you're getting.

**Comment by jy95** [comment]
Ok, I will follow what thebinarypenguin  said : with their branch ; https://github.com/raml-org/raml-js-parser-2/tree/develop . Let's hope it works

**Comment by jy95** [comment]
UPDATE : I succeded to read my raml file and access data inside with this project : https://github.com/raml2html/raml2obj (wrapper around raml-js-parser-2). Lastest version 8 days ago .... .

**Comment by jstoiko** [comment]
Parser version updated to 1.1.14 in the raml1.0 branch. 

@jy95, can you confirm that it solved this issue?

**Comment by jy95** [comment]
I tried, still nothing ... (I think their develop branch fixes a lot of mess in parser 1.1.14 ^^)

Only raml2obj has worked ... If https://github.com/mulesoft-labs/osprey-method-handler merge the RAML 1.0 pull request is merged and I got the new version, I can finish the little wrapper (maybe on NPM if I think it worthy XD) I am working on (fast explain : it will read the raml file , get the data to make osprey-router and osprey-method-handler work).

**Comment by jy95** [comment]
Thanks, They finally make it ... I will try
