### ISSUE TITLE
Resource Type Parameter not being properly handled

### ISSUE THREAD

**Issue by cmd-johnson** [mulesoft/osprey#134]
I'm currently testing the raml1.0 branch and encountered this error while testing resource types:

```
Error: Unknown type <<resourcePathName>> in {"test" {:name "test", :displayName "test", :typePropertyKind "TYPE_EXPRESSION", :type ["string"]}, :path [], :fixpoints #object [cljs.core.Atom {:val {}}]}
    at datatype_expansion$utils$error ([...]/osprey-test/node_modules/datatype-expansion/node/datatype_expansion/utils.js:42:8)
    at datatype_expansion$expanded_form$expanded_form_inner ([...]/osprey-test/node_modules/datatype-expansion/node/datatype_expansion/expanded_form.js:319:39)
    at [...]/osprey-test/node_modules/datatype-expansion/node/datatype_expansion/expanded_form.js:218:61
    at [...]/osprey-test/node_modules/datatype-expansion/node/cljs/core.js:17998:135
    at [...]/osprey-test/node_modules/datatype-expansion/node/cljs/core.js:19036:96
    at [...]/osprey-test/node_modules/datatype-expansion/node/cljs/core.js:19037:3
    at cljs.core.PersistentVector.cljs$core$IReduce$_reduce$arity$3 ([...]/osprey-test/node_modules/datatype-expansion/node/cljs/core.js:19052:3)
    at Function.cljs.core.reduce.cljs$core$IFn$_invoke$arity$3 ([...]/osprey-test/node_modules/datatype-expansion/node/cljs/core.js:7733:13)
    at Function.cljs.core.mapv.cljs$core$IFn$_invoke$arity$2 ([...]/osprey-test/node_modules/datatype-expansion/node/cljs/core.js:17997:52)
    at cljs$core$mapv ([...]/osprey-test/node_modules/datatype-expansion/node/cljs/core.js:17978:23)
```

Looks to me like `<<resourcePathName>>` is not properly replaced with `test` before it is passed on to the datatype-expansion module.

I managed to produce this error with this example:

### index.js
```js
#!/usr/bin/env node
const { join } = require('path')

require('osprey').loadFile(join(__dirname, 'test.raml'))
  .then(() => console.log('works as intended'))
  .catch(console.error)
```

### test.raml
```raml
#%RAML 1.0
title: test
mediaType: application/json
types:
  test: string
resourceTypes:
  testType:
    post:
      body:
        type: <<resourcePathName>>
/test:
  type: testType
```

**Comment by jstoiko** [comment]
The underlying library that expands datatypes after it parses the RAML file and before it loads it into Osprey does not support `<<resourcePathName>>` as a value of `type`. It would be a nice feature to have though. I created an [issue](https://github.com/raml-org/raml-parser-toolbelt/issues/53).

BTW, you might want to define your `test` type some properties, i.e.:
```raml
types:
  test: 
    properties:
      test_value: string
```

In the meantime, you'll have to avoid using `type: `, i.e.:
```raml
#%RAML 1.0
title: test
mediaType: application/json

types:
  test:
    properties:
      test_value: string

resourceTypes:
  testType:
    post:
      body:
        type: test

/test:
  type: testType

```

**Comment by cmd-johnson** [comment]
Okay, the `<<resourcePathName>>` case might be a little special.

However I did some digging, and if I'm not mistaken, the RAML 1.0 specification allows for this syntax:
```raml
#%RAML 1.0
title: test
mediaType: application/json

types:
  Client:
    properties:
      id: string

resourceTypes:
  collection:
    get:
      responses:
        200:
          body:
            <<resourceType>>[]

/clients:
  type: { collection: { resourceType: Client } }
```
After stepping through osprey's code, I found that in the `_expand` function in `expandTypes` in `lib/server.js`, osprey tries to expand the `<<resourceType>>` parameter from the example above within the `resourceTypes` object. Now that obviously cannot work, because that parameter is a placeholder that can only be replaced as soon as the parameter is assigned a value, which in this case only happens inside the `/clients`'s type definition.

`raml-1-parser` already takes care of replacing the `<<resourceType>>` parameter and the `/clients` resource ends up containing a 200 response with a body containing an array of `Client`s.

If I'm not mistaken, it should be fine to simply skip expanding Resource Types altogether to prevent this error from happening, since the application of Resource Types seems to be something `raml-1-parser` takes care of.

**Edit**

Actually, looking further, I found that `raml-1-parser` even handles the `<<resourcePathName>>` case and correctly expands it, so it doesn't appear to me like this is an Issue with the `datatype-expansion` module after all, but really with osprey trying to expand the `resourceType`-object.

**Comment by jstoiko** [comment]
You are totally right! 

Thanks for this. I'll review/comment your PR.

**Comment by cmd-johnson** [comment]
Sure thing, should I just put them to the type tests or should I add a new category for resource types?

**Comment by cmd-johnson** [comment]
Looking even further into the issue, I don't see anymore why you're expanding types at all - `raml-1-parser` takes care of all that and even the extensive [GitHub API example](https://github.com/raml-apis/GitHub) turns out exactly the same as before calling `expandTypes` in `server.js`.
