### ISSUE TITLE
Should generate an express app

### ISSUE THREAD

**Issue by blakeembrey** [mulesoft/osprey#14]
If I were using osprey, I would expect that it would create a express application which I could then use however I see fit. This means I could mount it to my normal application or use it as the base of the application. There are also a lot of benefits to this approach:

* Osprey applications will be self contained and don't affect parts of the users application
* The osprey app can be mounted any number of times on any number of routes
* You don't need to impose parsing logic onto the users application which can actually cause security concerns
* You can use the xml middleware in osprey without forcing it onto users (same with form encoding, json, etc.)

**Basic usage:**

```javascript
app.use('/api', osprey.create({
  ramlFile: path.join(__dirname, '/assets/raml/api.raml')
}));
```

**Example:**

```javascript
var api = osprey.create({
  ramlFile: path.join(__dirname, '/assets/raml/api.raml')
});

api.get('/resource', function(req, res) {
  //// Your business logic here!
});

app.use('/api', api);
```

**Comment by blakeembrey** [comment]
@cybertk I'm not after a scaffolding tool, I am after a mountable application instance (or middleware). Have a look at `master` for the rebuild Osprey instance I've been working on, it can work with Connect, Express or even HTTP servers which allowed me to build some more powerful concepts into the library.

**Comment by cybertk** [comment]
Great
