### ISSUE TITLE
Is osprey routing required now?

### ISSUE THREAD

**Issue by ty10r** [mulesoft/osprey#142]
In osprey before supporting RAML 1.0, our express routes were unaffected by the use of Osprey.

The documentation now seems to suggest that projects must use Osprey routes. Is this true?

`/user/:userId` used to be an acceptable route to use and Osprey would still act as a middleware for the route.
`/user/{userId}` seems to be required now.

Is this true? If so, why?

**Comment by jstoiko** [comment]
Are you referring to the README? Not much [changed](https://github.com/mulesoft/osprey/commit/6504ab08bcbb5c41a73a4b636dd95da5c3a208ed) there.

Can you show me an example of what used to work before (in v0.3.2) that doesn't work now (in v4.0.0)?

**Comment by ty10r** [comment]
I tagged this as a question because I'm not sure if it doesn't work.

Sounds like it should work to use express routes in our routers still. I'll look into it. Thanks for the response.
