### ISSUE TITLE
miltiple raml files

### ISSUE THREAD

**Issue by AndriiDidkivsky** [mulesoft/osprey#144]
Is there any way to handle multiple raml files?

**Comment by AndriiDidkivsky** [comment]
resolved.

**Comment by primeminister** [comment]
@AndriiDidkivsky how did you do that? Looking for it in the docs, but cannot find it.

**Comment by AndriiDidkivsky** [comment]
@primeminister , i use [osprey-mock-service](https://github.com/mulesoft-labs/osprey-mock-service) and call it multiple times for each raml file. This solution is enough for my use case. Look [here line 73](https://github.com/AndriiDidkivsky/raml-gitlab-mock/blob/master/server.js#L73). Of course you can't use it.
