### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by jy95** [mulesoft/osprey#145]
Hello,

I discover a issue with optional object : 

Here is my traits : 

-  queryParameters.raml : [ queryParameters.raml](https://github.com/mulesoft/osprey/files/970898/traits.txt)
- answers.raml : [answers.raml](https://github.com/mulesoft/osprey/files/970921/answers.txt)

My main raml (in its short size version) : 
```raml
#%RAML 1.0
title: Some Api
baseUri: localhost:3000/{version}
version: v1
mediaType: application/json
protocols: [HTTP]

uses:
    queryParameters:  libraries/queryParameters.raml
    Answers:     libraries/answers.raml

/calls:
    description: Collection of  registered calls
    get:
        description: Get a list of  registered calls
        is: [queryParameters.limits, queryParameters.order, queryParameters.date]
        responses:
            200:
                body:
                    application/json:
                      type: Answers.Calls
```
I got this message when testing : 
```bash
curl 'http://localhost:3000/v1/calls'
```

and the result
```js
{
  "message": "Cannot convert undefined or null to object",
  "status": 404
}
```

If I add an date and url encode the url, it works. How can I get a result even the data is undefined ?

Any idea  ?

PS: I have done this issue very fast. Don't hesistate to ask a revision of this code snippet.

EDIT: Looks like an issue from the parser : https://github.com/raml-org/raml-js-parser-2/issues/713

**Comment by jstoiko** [comment]
Hi @jy95, the issue seems resolved in the parser. Did it solve your issue above?

**Comment by jy95** [comment]
Not tested : I didn't touch RAMl stuff since 2-3 months
