### ISSUE TITLE
Basic HTTP Authentication: add the support for the passport option "passReqToCallback"

### ISSUE THREAD

**Issue by jmesters** [mulesoft/osprey#147]
For basic authentication, [Passport-http](https://github.com/jaredhanson/passport-http/blob/master/lib/passport-http/strategies/basic.js) has the option *passReqToCallback* to add *req* as the callback's first parameter.

I'd like to use it in the options defined in Osprey when calling *loadFile*.
Something like that:
```javascript
    osprey.loadFile(raml, {
        security: {
            token_auth: function () {
                return { handler: security.token_auth }
            },
            basic_auth: {
                realm: 'API', // Optional
                passReqToCallback: true,
                validateUser: security.basic_auth
            }
        }
    })
...
```

From what I can see in Osprey's [security handler](https://github.com/mulesoft/osprey/blob/master/lib/security/handler.js) (function *createBasicAuthHandler*) the only supported option is *realm*.

Thanks!

**Comment by sichvoge** [comment]
Thanks for the suggestion @jmesters. We will take a look at soon as possible. Currently, a bit swamped with other things. So apologies for any delays.

**Comment by jstoiko** [comment]
@jmesters, you're right. It would be nice to support that parameter in Osprey since the underlying lib, passport-http, [supports it for Basic auth](https://github.com/jaredhanson/passport-http/blob/master/lib/passport-http/strategies/basic.js#L52) (passes it to passport).

Feel free to submit a PR if you have time.

**Comment by jstoiko** [comment]
* note that you can also have your own [custom security scheme](https://github.com/mulesoft/osprey#custom-security-schemes) in which case you'd have access to the request in the handler function. Might not be what you want but adding this as a side note for the record.

**Comment by jmesters** [comment]
Thanks, I've created my first ever public pull request : #148
