### ISSUE TITLE
Is this project still actively maintained or already deprecated?  

### ISSUE THREAD

**Issue by timur-han** [mulesoft/osprey#153]
Hello,

Is this project still actively maintained / developed? The project activity seems to be more deprecated. This question is quite relevant for potential users / adopters, that's why I am asking.

**Comment by jstoiko** [comment]
It is. Sometimes projects get to a certain maturity level and don't get as many commits/releases as before. The latest few releases of Osprey brought RAML 1.0 support, that was a major one.

If you feel that some features are missing or would be worth discussing, you are welcome to add your contribution or start a discussion here. I hope that helps.

**Comment by fedotov** [comment]
Does response validation implementation planed in near future?

**Comment by jstoiko** [comment]
There hasn't been a need for it in the projects that I have been involved but I can see how this may be useful in some cases. @timur-han @fedotov: if you have a need for it, feel free to submit a PR.

**Comment by timur-han** [comment]
Okay, just to clarify this open question: The project is actively maintained except that features planned, such as "Built-in Response Handling Coming soon", and certain bug fixes need to be done by the reporters themselves :)

**Comment by jstoiko** [comment]
at the end of the day, maintainers are users and vice-versa. why draw a line? isn’t this what Open Source is all about?

**Comment by timur-han** [comment]
Yea that depends on how you define a maintainer.  For me there is a
difference between a commiter, a contributor, a user, and a maintainer but
probably there is no need for such a discussion here :)

https://opensource.guide/leadership-and-governance/

Am 24.01.2018 17:04 schrieb "Jonathan Stoikovitch" <notifications@github.com
>:

at the end of the day, maintainers are users and vice-versa. why draw a
line? isn’t this what Open Source is all about?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mulesoft/osprey/issues/153#issuecomment-360182372>, or mute
the thread
