### ISSUE TITLE
Allow using middlewares when defining a new api.

### ISSUE THREAD

**Issue by mcorbanini** [mulesoft/osprey#60]
I need to define authenticated apis using passport authentication method and a custom object that handle permissions. 

If I define this api example against express `app`, it work as well. But with the object that `osprey.create` returns, it always gives me `404`:

```javascript
var api = osprey.create('/api', app, {
  ramlFile: path.join(__dirname, '../raml_spec/api_spec.raml'),
  logLevel: app.get('env') !== 'test' ? 'debug' : 'off'
});

api.describe(function (api) {
  api.put(
    '/templates/:id',
    accountController.ensureAuthenticated, 
    permissions.can('edit'),                           
    templatesController.edit);                     
})
.then(function() {
  app.listen(app.get('port'), function() {
    debug('Express server listening on port ' + server.address().port);
  });
})
```

Thanks!

**Comment by blakeembrey** [comment]
We're accepting PRs against the `0.1.x` branch if this is still an issue, but `0.1.x` is deprecated and replaced with `0.2.0`.
