### ISSUE TITLE
Mock data module roadmap?

### ISSUE THREAD

**Issue by jewelsjacobs** [mulesoft/osprey#65]
Hi!

I was wondering if there was some code somewhere I could hack on with the beginnings of the mock data cli module for osprey 0.2.0-alpha.

I'm starting to use that app I have and could REALLY REALLY use the ability to serve the example json responses as mock data based on the baseUrl and defined routes in the raml.

If there isn't anything hacked out yet, any pointers would be most helpful.

Thanks for all of your help.  I'll try not to be too impatient. :)

**Comment by blakeembrey** [comment]
Hi @jewelsjacobs! There's nothing available yet and I'm flying the next couple of days, but expect something after that. Feel free to give it a shot too, it should just be a matter of iterating over the RAML object after you've attached Osprey and attaching a bunch of response handles based on the examples. However, I'll probably get around to this end at the end of the week too :smile:

**Comment by jewelsjacobs** [comment]
Hey @blakeembrey! I'll see if I can hack something out while you're out and about. Enjoy your travels. :globe_with_meridians:

**Comment by blakeembrey** [comment]
@jewelsjacobs Sorry for the delay! Things are crazy but I managed to get some code in and push out https://github.com/mulesoft-labs/osprey-mock-service for you to try. Let me know if it works for you :smile:
