### ISSUE TITLE
No "loadFile" method on local install of Osprey

### ISSUE THREAD

**Issue by davidfells** [mulesoft/osprey#70]
Installed per directions (npm install osprey --save) along with the example script (from the Readme) 

TypeError: Object #<Object> has no method 'loadFile'
    at Object.<anonymous> (/Users/david_fells/projects/inmar_cdm/index.js:6:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

Quick search in node_modules/osprey shows no loadFile method - comparing the npm install to what's in Github, the packages look radically different.

**Comment by davidfells** [comment]
Cloning the repo into my node_modules directory then running npm install inside the osprey directory seems to let the app run. Not the process I would've expected, however. Is that the intended use?

**Comment by SimenB** [comment]
Probably a dependency that's a devDep that should have been a regular dep

**Comment by blakeembrey** [comment]
@davidfells What version of Osprey did you have installed?

**Comment by davidfells** [comment]
It's whatever you get from a regular npm install. I've since removed it from my project, but it was reproduceable by npm installing it and looking at the payload.

**Comment by blakeembrey** [comment]
@davidfells Mine installs `osprey@0.1.1` if I don't specify the version, and that release is an entirely different beast to the current release on `master`. Look at that release here: https://github.com/mulesoft/osprey/tree/0.1.x. If you want to install the latest version on `master`, try `npm i osprey@0.2.0-beta.1`.

**Comment by davidfells** [comment]
I'll try that and report back. Thanks
