### ISSUE TITLE
Installation fails with node v0.12

### ISSUE THREAD

**Issue by sirapu** [mulesoft/osprey#73]
Hi together,

Installation fails with node v0.12  -  specially libxmljs fails. For node v0.12 I use libxmljs@0.14
Though I could succesfully install the osprey-mockup-service.

 /usr/local/lib/node_modules/npm/bin/node-gyp-bin/node-gyp: line 3: node: command not found
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.12.1"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.12.1"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.12.1"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.12.1"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7","npm":"2.12.1"})
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "osprey"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! libxmljs@0.8.1 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the libxmljs@0.8.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/apandit/npm-debug.log

**Comment by blakeembrey** [comment]
@sirapu `libxmljs` has been an optional dependency for a while, but with the latest code on `master` its been removed altogether and made a manual install. What version of Osprey are you trying to use? I'll make a release of master now too, since there's been some API changes.

**Comment by blakeembrey** [comment]
Closing this for now. Let me know if you have issues installing the latest version.
