### ISSUE TITLE
API version is not enforced

### ISSUE THREAD

**Issue by greenrd** [mulesoft/osprey#75]
The RAML spec is not very clear on this point, but Osprey allows anything to be supplied as the {version} parameter in the baseUri, in the actual URL - it does not check that the value of {version} in the actual URL matches the API version declared. Shouldn't it check?

**Comment by greenrd** [comment]
P.S. we are using https://github.com/mulesoft-labs/osprey-mock-service - not sure whether I should have filed this issue against this repo or that repo.

**Comment by blakeembrey** [comment]
@greenrd You're right, the check isn't currently enforced. It's a quick patch and it definitely helps to log it on the mocking service, where it's related, but I'll see it either way :smile:

**Comment by blakeembrey** [comment]
Fixed and released with https://github.com/mulesoft-labs/osprey-mock-service/releases/tag/v0.0.11
