### ISSUE TITLE
Headers only defined in security scheme are removed from the request

### ISSUE THREAD

**Issue by cpetrov** [mulesoft/osprey#79]
Custom headers used to describe a security scheme get removed from the request if only the security scheme is referenced, e.g.:

``` raml
securitySchemes:
  - custom_auth:
      type: x-custom-auth
      describedBy:
        headers:
          Custom-Token:
            type: string
...

/foo:
  get: 
    securedBy: [custom_auth]
```

In this example the `custom-token` header is stripped from the request. This works:

``` raml
securitySchemes:
  - custom_auth:
      type: x-custom-auth
      describedBy:
        headers:
          Custom-Token:
            type: string
...

/foo:
  get: 
    securedBy: [custom_auth]
    headers:
      Custom-Token:
        type: string
```

One would expect security headers to be recognised from the scheme and not to be stripped from the request. Declaring them for each entry point is redundant.

**Comment by blakeembrey** [comment]
That's a great catch, thanks! :+1: I'll be sure to fix it. A quick question on this - could you make use of the security layer here? I'd love a little more context on the usage of the header in the application (if it's aside from authentication).

**Comment by cpetrov** [comment]
In my case no - the token was only delegated to another service.

**Comment by sallespro** [comment]
hi, i am having a problem authenticating with passport-jwt following @gciatto 's approach as shown in https://github.com/mulesoft/osprey/issues/102

would it be a victim of the header removal as well !?

i noticed in passport's strategy verify function the token payload is received in the request, but seems to be `unauthorized` funrther along the middleware, in Osprey.

**Comment by jstoiko** [comment]
@cpetrov: #160 should address your issue.
