### ISSUE TITLE
Timeline for support with RAML 1.0

### ISSUE THREAD

**Issue by Shockolate** [mulesoft/osprey#81]
I know RAML 1.0 was released a month ago, but I'm curious as to when support will be added to Osprey.

**Comment by blakeembrey** [comment]
@Shockolate Absolutely on the roadmap for me, I'm hoping to release it late January or early February. There's a couple of tricky things that have zero implementation which could make this harder, such as zero public implementations of the type system in validation yet. That might make the implementation much more time consuming. Right now though, I'm currently blocked on a stable RAML JavaScript parser that I can use from NPM.

**Comment by eberls** [comment]
Anything we can do to preview/help with this?

**Comment by blakeembrey** [comment]
The JavaScript parser is still churning along, I believe it's closer to possible for me to use. The first thing I'd need to do is be able to transform the Osprey dependency projects in a way that the new parser objects look. I haven't started that yet, but if someone wants to open a PR with some work on it I can definitely take a look at it.

For example:

* https://github.com/mulesoft-labs/osprey-method-handler
* https://github.com/mulesoft-labs/osprey-resources
* https://github.com/mulesoft-labs/osprey-router

**Comment by d3mi3n** [comment]
Is there any clear timeline when support for RAML 1.0 will be available?

**Comment by artemkaint** [comment]
+100 waiting

**Comment by neilhosey** [comment]
+1 would love to know when this is coming!

**Comment by neilhosey** [comment]
RC2 is released and we now have a parser :) 

Would be great to know when this is coming out?

**Comment by blakeembrey** [comment]
I'm no longer involved with the project, hopefully someone else from @mulesoft can let you know 😄

**Comment by jstoiko** [comment]
v0.4.0 with RAML 1.0 [released](https://github.com/mulesoft/osprey/releases/tag/v0.4.0)
