### ISSUE TITLE
Fails to load raml which has a schema included 

### ISSUE THREAD

**Issue by ivantv** [mulesoft/osprey#90]
I have the following api.raml, userId.yaml and index.js defined. But when i run the node index.js. It exits. Is this a bug? How to debug this issue ?

But when i directly include the json schema in api. raml it starts working
## api.raml (userId schema is external userId.yaml file) NOT WORKING 
# %RAML 0.8

title: Messages API
version: v1
baseUri: http://127.0.0.1:3004/api
schemas:
- !include userId.yaml
  /test:
  post:
    description: |
      Send a message to a user.
    body:
      application/json:
        schema: userId
## userId.yaml

userId:|{
    "$schema": "http:\/\/json-schema.org\/draft-03\/schema",
    "type": "object",
    "required": true,
    "properties": {
       "userId": {
           "type": "string",
           "pattern": "[a-zA-Z0-9]+",
           "required": true
       }
    }
}
## index.js

var express = require('express')
var osprey = require('osprey')
var join = require('path').join

var PORT = process.env.PORT || 3004

var router = osprey.Router()
router.get('/test', function (req, res) {
  res.json([
    {
      username: 'blakeembrey',
      password: 'hunter2'
    }
  ])
})

osprey.loadFile(join(__dirname, 'api.raml'))
  .then(function (middleware) {
    var app = express()

```
app.use('/api', middleware, router)

app.listen(PORT, function () {
  console.log('Application listening on ' + PORT + '...')
})
```

  })
## api.raml (WORKING)
# %RAML 0.8

title: Messages API
version: v1
baseUri: http://127.0.0.1:3004/api
/test:
  post:
    description: |
      Send a message to a user.
    body:
      application/json:
        schema: |
          {
            "$schema": "http:\/\/json-schema.org\/draft-03\/schema",
            "type": "object",
            "required": true,
            "properties": {
              "userId": {
                "type": "string",
                "pattern": "[a-zA-Z0-9]+",
                "required": true
              }
            }
          }

**Comment by blakeembrey** [comment]
Can you please format the code samples? It makes it much easier to debug. Just wrap the blog in three backticks with the optional language:

~~~md
```js
```
~~~

**Comment by blakeembrey** [comment]
You can also use the error handler of the promise to check what's going on. Most likely there's a parsing issue:

```js
promise
  .then(function () { ... })
  .catch(function (err) {
    console.log(err)
  })
```

**Comment by blakeembrey** [comment]
It's hard to tell without formatting, but I would guess it's caused by `userId.yaml` being a map instead of a list of maps.
